CREATE TABLE employees (
    employee_id VARCHAR(64) PRIMARY KEY,
    full_name VARCHAR(200) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role_code VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE facilities (
    facility_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_name VARCHAR(150) NOT NULL,
    description VARCHAR(2000),
    category VARCHAR(100),
    icon VARCHAR(100),
    published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_facilities_name UNIQUE (facility_name)
);

CREATE TABLE facility_fields (
    field_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL,
    label VARCHAR(150) NOT NULL,
    field_type VARCHAR(50) NOT NULL,
    placeholder VARCHAR(255),
    required BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 1,
    validation_json VARCHAR(4000),
    default_value VARCHAR(1000),
    field_options JSON,
    CONSTRAINT fk_facility_fields_facility FOREIGN KEY (facility_id)
        REFERENCES facilities (facility_id) ON DELETE CASCADE
);

CREATE TABLE facility_rules (
    rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL,
    booking_deadline TIME,
    booking_start_time TIME,
    CONSTRAINT uq_facility_rules_facility UNIQUE (facility_id),
    CONSTRAINT fk_facility_rules_facility FOREIGN KEY (facility_id)
        REFERENCES facilities (facility_id) ON DELETE CASCADE
);

CREATE TABLE bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL,
    employee_id VARCHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    booking_date DATE NOT NULL,
    cancelled_at TIMESTAMP,
    booking_response JSON,
    CONSTRAINT fk_bookings_facility FOREIGN KEY (facility_id)
        REFERENCES facilities (facility_id),
    CONSTRAINT fk_bookings_employee FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id)
);

CREATE TABLE audit_logs (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id VARCHAR(64),
    actor_role VARCHAR(32) NOT NULL,
    action_code VARCHAR(100) NOT NULL,
    entity_name VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80) NOT NULL,
    old_value_json VARCHAR(8000),
    new_value_json VARCHAR(8000),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(64)
);

CREATE INDEX idx_facility_fields_facility ON facility_fields (facility_id);
CREATE INDEX idx_bookings_facility ON bookings (facility_id);
CREATE INDEX idx_bookings_employee ON bookings (employee_id);
CREATE INDEX idx_bookings_employee_date ON bookings (employee_id, booking_date);
CREATE INDEX idx_audit_logs_actor ON audit_logs (actor_id);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_name, entity_id);
