CREATE TABLE employees (
    employee_id VARCHAR(64) PRIMARY KEY,
    full_name VARCHAR(200) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role_code VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE facilities (
    facility_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_name VARCHAR(150) NOT NULL,
    description VARCHAR(2000),
    category VARCHAR(100),
    icon VARCHAR(100),
    status BOOLEAN NOT NULL DEFAULT TRUE,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_facilities_name UNIQUE (facility_name)
);

CREATE TABLE facility_fields (
    field_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL,
    label VARCHAR(150) NOT NULL,
    field_type VARCHAR(50) NOT NULL,
    placeholder VARCHAR(255),
    required BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 1,
    validation_json VARCHAR(4000),
    default_value VARCHAR(1000),
    CONSTRAINT fk_facility_fields_facility FOREIGN KEY (facility_id)
        REFERENCES facilities (facility_id) ON DELETE CASCADE
);

CREATE TABLE field_options (
    option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id BIGINT NOT NULL,
    option_value VARCHAR(255) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_field_options_field FOREIGN KEY (field_id)
        REFERENCES facility_fields (field_id) ON DELETE CASCADE
);

CREATE TABLE facility_rules (
    rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL,
    booking_deadline TIME,
    booking_start_time TIME,
    reminder_time TIME,
    qr_required BOOLEAN NOT NULL DEFAULT FALSE,
    allow_cancellation BOOLEAN NOT NULL DEFAULT TRUE,
    maximum_capacity INTEGER,
    regular_commute_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_facility_rules_facility UNIQUE (facility_id),
    CONSTRAINT fk_facility_rules_facility FOREIGN KEY (facility_id)
        REFERENCES facilities (facility_id) ON DELETE CASCADE
);

CREATE TABLE bookings (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id BIGINT NOT NULL,
    employee_id VARCHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL,
    qr_code VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    booking_date DATE NOT NULL,
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_bookings_facility FOREIGN KEY (facility_id)
        REFERENCES facilities (facility_id),
    CONSTRAINT fk_bookings_employee FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id)
);

CREATE TABLE booking_responses (
    response_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    field_id BIGINT NOT NULL,
    response_value VARCHAR(2000) NOT NULL,
    CONSTRAINT fk_booking_responses_booking FOREIGN KEY (booking_id)
        REFERENCES bookings (booking_id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_responses_field FOREIGN KEY (field_id)
        REFERENCES facility_fields (field_id)
);

CREATE TABLE notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id VARCHAR(64) NOT NULL,
    booking_id BIGINT,
    notification_type VARCHAR(60) NOT NULL,
    channel_code VARCHAR(40) NOT NULL,
    message_body VARCHAR(4000) NOT NULL,
    sent_at TIMESTAMP,
    status_code VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_employee FOREIGN KEY (employee_id)
        REFERENCES employees (employee_id),
    CONSTRAINT fk_notifications_booking FOREIGN KEY (booking_id)
        REFERENCES bookings (booking_id)
);

CREATE TABLE audit_logs (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id VARCHAR(64),
    actor_role VARCHAR(32) NOT NULL,
    action_code VARCHAR(100) NOT NULL,
    entity_name VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80) NOT NULL,
    old_value_json VARCHAR(8000),
    new_value_json VARCHAR(8000),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(64)
);

CREATE INDEX idx_facility_fields_facility ON facility_fields (facility_id);
CREATE INDEX idx_field_options_field ON field_options (field_id);
CREATE INDEX idx_bookings_facility ON bookings (facility_id);
CREATE INDEX idx_bookings_employee ON bookings (employee_id);
CREATE INDEX idx_bookings_employee_date ON bookings (employee_id, booking_date);
CREATE INDEX idx_booking_responses_booking ON booking_responses (booking_id);
CREATE INDEX idx_notifications_employee ON notifications (employee_id);
CREATE INDEX idx_audit_logs_actor ON audit_logs (actor_id);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_name, entity_id);
