BEGIN;

-- Real employee data imported from Filter Results.xlsx + Filter Results (1).xlsx
-- Total: 783 employees (Hyderabad + Kolkata, de-duplicated by email)
-- employee_id : email prefix, dots/specials -> underscore, uppercase
-- role_code   : mapped from Department column (see mapping below)
-- work_mode   : HYBRID (update per employee if needed)
-- password_hash: NULL -> backend falls back to default password123
--
-- Mapping:
--   Cloud Platform Engineering, Global Cloud Services -> DEVOPS
--   Accounting and Finance, Strategic Sourcing        -> FINANCE
--   Human Resources                                   -> HR
--   Product Management                                -> MANAGER
--   Customer Operations, Customer Success, Facilities,
--   Global Services, Managed Services, Services Delivery,
--   Technical Support                                 -> OPS
--   Technology, Information Systems, Legal,
--   Research and Development, <other>                 -> EMPLOYEE

INSERT INTO employees
  (employee_id, full_name, email, department, role_code, work_mode, office_location, active)
VALUES
  ('ANURAG_ANUPAM', 'Anurag Anupam', 'Anurag.Anupam@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('VAMSHIKRISHNA_BALLA', 'VamshiKrishna Balla', 'VamshiKrishna.Balla@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SUDHA_MADHURI', 'Sudha Madhuri', 'Sudha.Madhuri@hyland.com', 'Customer Success', 'OPS', 'HYBRID', 'HYDERABAD', FALSE),
  ('NAVEEN_KONDA', 'Naveen Konda', 'Naveen.Konda@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SIDDA_SAIKIRAN', 'Sidda Saikiran', 'Sidda.Saikiran@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('ARGHA_MUKHERJEE', 'Argha Mukherjee', 'Argha.Mukherjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('BISWARUP_DAS', 'Biswarup Das', 'Biswarup.Das@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SANGEETH_P', 'Sangeeth P', 'Sangeeth.P@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('NAVEEN_MADDIPATI', 'Naveen Maddipati', 'Naveen.Maddipati@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('NAVEEN_KUMARG', 'Naveen Kumarg', 'Naveen.Kumarg@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SAICHARAN_SOMISETTY', 'Saicharan Somisetty', 'Saicharan.Somisetty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SAIKIRAN_VANGALA', 'Saikiran Vangala', 'Saikiran.Vangala@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('YASHIKA_AGGARWAL', 'Yashika Aggarwal', 'Yashika.Aggarwal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('VANITHA_TENTU', 'Vanitha Tentu', 'Vanitha.Tentu@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', FALSE),
  ('NEHA_REDDY', 'Neha Reddy', 'Neha.Reddy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('BANTY_MUKHERJEE', 'Banty Mukherjee', 'Banty.Mukherjee@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SRILAKSHMI_PURIMITLA', 'Srilakshmi Purimitla', 'Srilakshmi.Purimitla@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('ARPITKUMAR_MOHANTY', 'Arpitkumar Mohanty', 'Arpitkumar.Mohanty@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('ADEEBA_SAMAN', 'Adeeba Saman', 'Adeeba.Saman@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('AASHIKA_VIJAYAN', 'Aashika Vijayan', 'Aashika.Vijayan@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('ABDULSHAKOOR_KHAN', 'Abdulshakoor Khan', 'Abdulshakoor.Khan@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('HEMAVARNA_S', 'Hemavarna S', 'Hemavarna.S@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('NISHANTH_R', 'Nishanth R', 'Nishanth.R@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('AVINASH_VELAGALA', 'Avinash Velagala', 'Avinash.Velagala@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', FALSE),
  ('REMANSHU_GOYAL', 'Remanshu Goyal', 'Remanshu.Goyal@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('MOHAMMADFATHIR_HUSSAIN', 'MohammadFathir Hussain', 'MohammadFathir.Hussain@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('KUSHAGRA_SARAF', 'Kushagra Saraf', 'Kushagra.Saraf@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('ABHIJEET_DASH', 'Abhijeet Dash', 'Abhijeet.Dash@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('RINKI_JHA', 'Rinki Jha', 'Rinki.Jha@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('VISHAL_AGRAWAL', 'Vishal Agrawal', 'Vishal.Agrawal@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SUBHAM_DALAI', 'Subham Dalai', 'Subham.Dalai@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SUNVISH_CHARAK', 'Sunvish Charak', 'Sunvish.Charak@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('ENOCH_LAL', 'Enoch Lal', 'Enoch.Lal@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('ARAVIND_GOWRU', 'Aravind Gowru', 'Aravind.Gowru@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('MADHAVI_MENAVATH', 'Madhavi Menavath', 'Madhavi.Menavath@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('JOANNA_SHARON', 'Joanna Sharon', 'Joanna.Sharon@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('JIGNAS_YELLA', 'Jignas Yella', 'Jignas.Yella@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SARANADITHYA_RS', 'Saran Adithya R S', 'Saranadithya.Rs@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('ANANDHI_A', 'Anandhi A', 'Anandhi.A@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('ADITI_VERMA', 'Aditi Verma', 'Aditi.Verma@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SHREYANSHI_GUPTA', 'Shreyanshi Gupta', 'Shreyanshi.Gupta@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('RAKESH_PEDDI', 'Rakesh Peddi', 'Rakesh.Peddi@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('MAITREYA_SAHU', 'Maitreya Sahu', 'Maitreya.Sahu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('ALISHA_KANURI', 'Alisha Kanuri', 'Alisha.Kanuri@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('RACHIT_SRIVASTAVA', 'Rachit Srivastava', 'Rachit.Srivastava@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('DIVYASREE_GOTTIPATI', 'Divyasree Gottipati', 'Divyasree.Gottipati@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('DINESH_MOHAPATRA', 'Dinesh Mohapatra', 'Dinesh.Mohapatra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SYED_ARSHAD', 'Syed Arshad', 'Syed.Arshad@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SRIRANJANI_GOPIKRISHNAN', 'Sriranjani Gopikrishnan', 'Sriranjani.Gopikrishnan@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'HYDERABAD', TRUE),
  ('SUBHASHREE_B', 'Subhashree B', 'Subhashree.B@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('ASHOK_S', 'Ashok S', 'Ashok.S@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('DEEPIKA_KAKARLAPUDI', 'Deepika Kakarlapudi', 'Deepika.Kakarlapudi@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SOMA_KODURU', 'Soma Koduru', 'Soma.Koduru@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('KISHORE_S', 'Kishore S', 'Kishore.S@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('CHAARULATHA_N', 'Chaarulatha N', 'Chaarulatha.N@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('MAMATHA_KOMIRINENI', 'Mamatha Komirineni', 'Mamatha.Komirineni@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('JANPAT_SAHITHI', 'Janpat Sahithi', 'Janpat.Sahithi@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('NIHITHA_MAMIDI', 'Nihitha Mamidi', 'Nihitha.Mamidi@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('RUCHITHA_REDDY', 'Ruchitha Reddy', 'Ruchitha.Reddy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('AROKIA_MARTINN', 'Arokia Martinn', 'Arokia.Martinn@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('YUKTHIKA_SS', 'Yukthika S S', 'Yukthika.SS@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SARANDA_PODDAR', 'Saranda Poddar', 'Saranda.Poddar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SIVA_V', 'Siva V', 'Siva.V@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SRIKANTH_AAKUTHOTA', 'Srikanth Aakuthota', 'Srikanth.Aakuthota@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('VIKAS_TRIPATHI', 'Vikas Tripathi', 'Vikas.Tripathi@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('RAGHAVENDRA_NIMAKAYALA', 'Raghavendra Nimakayala', 'Raghavendra.Nimakayala@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('NAGAKOUSHIK_MUNAGA', 'Naga Koushik Munaga', 'Nagakoushik.Munaga@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SANDEEP_DOSAPATI', 'Sandeep Dosapati', 'Sandeep.Dosapati@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SUDARSHAN_BUSHI', 'Sudarshan Bushi', 'Sudarshan.Bushi@hyland.com', 'Facilities', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('ASHISH_KUMARPANDEY', 'Ashish Kumar Pandey', 'Ashish.Kumarpandey@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SWAROOP_KULKARNI', 'Swaroop Kulkarni', 'Swaroop.Kulkarni@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('NANCY_DAGAR', 'Nancy Dagar', 'Nancy.Dagar@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SANGHARAJ_PARULEKAR', 'Sangharaj Parulekar', 'Sangharaj.Parulekar@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('RUTURAJ_SHINDE', 'Ruturaj Shinde', 'Ruturaj.Shinde@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('DHANALAKSHMI_GORRELA', 'Dhanalakshmi Gorrela', 'Dhanalakshmi.Gorrela@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('BHARATH_BOMMIDI', 'Bharath Bommidi', 'Bharath.Bommidi@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('RUSHIKESH_SHINDE', 'Rushikesh Shinde', 'Rushikesh.Shinde@hyland.com', 'Technical Support', 'OPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('PRADEEP_GANESH', 'Pradeep Ganesh', 'Pradeep.Ganesh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('ANAND_PEDDURI', 'Anand Pedduri', 'Anand.Pedduri@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('ANIL_BUCHIMGARI', 'Anil Buchimgari', 'Anil.Buchimgari@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('INDRASENAREDDY_UDUMULA', 'Indrasenareddy Udumula', 'Indrasenareddy.Udumula@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SRINIVAS_S', 'Srinivas S', 'Srinivas.S@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('KISHOR_BAIRISHETTI', 'Kishor Bairishetti', 'Kishor.Bairishetti@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'HYDERABAD', TRUE),
  ('RITHEKHA_K', 'Rithekha K', 'Rithekha.K@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('PHANINDRA_SIDHANTHI', 'Phanindra Sidhanthi', 'Phanindra.Sidhanthi@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('RAHUL_RAJPOOT', 'Rahul Rajpoot', 'Rahul.Rajpoot@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('MAHENDER_JATTA', 'Mahender Jatta', 'Mahender.Jatta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('SHILPA_KODATI', 'Shilpa Kodati', 'Shilpa.Kodati@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('MAHENDER_AITHA', 'Mahender Aitha', 'Mahender.Aitha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('SHREYA_SHINGADE', 'Shreya Shingade', 'Shreya.Shingade@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('VISHNU_GANGICHETTY', 'Vishnu Gangichetty', 'Vishnu.Gangichetty@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SUREKHA_JAKNALLI', 'Surekha Jaknalli', 'Surekha.Jaknalli@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SRIDHAR_REDDY', 'Sridhar Reddy', 'Sridhar.Reddy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SHEKAR_REDDYSAMA', 'Shekar Reddysama', 'Shekar.Reddysama@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('SUDHIR_TIRUMALAGIRI', 'Sudhir Tirumalagiri', 'Sudhir.Tirumalagiri@hyland.com', 'Legal', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('NIKHIL_VANKADARA', 'Nikhil Vankadara', 'Nikhil.Vankadara@hyland.com', 'Legal', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('VIVIAN_DSOUZA', 'Vivian Dsouza', 'Vivian.Dsouza@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('KARTHIK_SV', 'Karthik SV', 'Karthik.Sv@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'HYDERABAD', TRUE),
  ('KUMARAN_SASIKANTHAN', 'Kumaran Sasikanthan', 'Kumaran.Sasikanthan@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('RAGHAVENDRA_JAGIRDAR', 'Raghavendra Jagirdar', 'Raghavendra.Jagirdar@hyland.com', 'Legal', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('KRISHNA_KAMBALA', 'Krishna Kambala', 'Krishna.Kambala@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'HYDERABAD', TRUE),
  ('AKSHITHA_KOPPAKA', 'Akshitha Koppaka', 'Akshitha.Koppaka@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('VENKATASATHYANARAYANA_CHAMAKURA', 'Venkatasathyanarayana Chamakura', 'Venkatasathyanarayana.Chamakura@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SOWBAKIYA_ARUMUGAM', 'Sowbakiya Arumugam', 'Sowbakiya.Arumugam@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SURYA_PRAKASH', 'Surya Prakash', 'Surya.Prakash@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('YOGESH_CHEEKOTI', 'Yogesh Cheekoti', 'Yogesh.Cheekoti@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('BHAGYALAKSHMI_BURSU', 'Bhagyalakshmi Bursu', 'Bhagyalakshmi.Bursu@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('VANJINATHAN_RAJENDRAN', 'Vanjinathan Rajendran', 'Vanjinathan.Rajendran@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('BHARATHIRAJA_PICHAYMANI', 'Bharathiraja Pichaymani', 'Bharathiraja.Pichaymani@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SAIDILEEP_VARISETTY', 'Saidileep Varisetty', 'Saidileep.Varisetty@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('PALLA_SURENDRA', 'Palla Surendra', 'Palla.Surendra@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('KARTHIK_MAJJI', 'Karthik Majji', 'Karthik.Majji@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SIVABHARATH_MATTA', 'SivaBharath Matta', 'SivaBharath.Matta@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('LALITH_MOTAY', 'Lalith Motay', 'Lalith.Motay@hyland.com', 'Legal', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('BISWAJIT_ROUT', 'Biswajit Rout', 'Biswajit.Rout@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'HYDERABAD', FALSE),
  ('VARUNCHAKRI_BORRU', 'Varunchakri Borru', 'Varunchakri.Borru@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SOUMEN_CHAKRABORTY', 'Soumen Chakraborty', 'Soumen.Chakraborty@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', FALSE),
  ('SNEHASHIS_DAS', 'Snehashis Das', 'Snehashis.Das@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('DARGASAI_KIRAN', 'Dargasai Kiran', 'Dargasai.Kiran@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('NARESH_KUMAR', 'Naresh Kumar', 'Naresh.Kumar@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('ANIL_THANNIRU', 'Anil Thanniru', 'Anil.Thanniru@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('YERRAGORLA_VIVEK', 'Yerragorla Vivek', 'Yerragorla.Vivek@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('RAJA_SAHA', 'Raja Saha', 'Raja.Saha@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SRILAKSHMIGANGA_THOTA', 'Srilakshmi Ganga Thota', 'SrilakshmiGanga.Thota@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SRIDHANYA_MALLE', 'Sridhanya Malle', 'Sridhanya.Malle@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('NAVEEN_CHILUKURI', 'Naveen Chilukuri', 'Naveen.Chilukuri@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SOWMYA_BURRA', 'Sowmya Burra', 'Sowmya.Burra@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SHIVA_NEELAM', 'Shiva Neelam', 'Shiva.Neelam@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('MOUNIKA_VALLABHU', 'Mounika Vallabhu', 'Mounika.Vallabhu@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('DOLLY_MEKA', 'Dolly Meka', 'Dolly.Meka@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('NIKHIL_JILLA', 'Nikhil Jilla', 'Nikhil.Jilla@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('AILI_VARSHITH', 'Aili Varshith', 'Aili.Varshith@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('RAJA_TUPAKULA', 'Raja Tupakula', 'Raja.Tupakula@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('BIBINOREEN_AYESHA', 'Bibinoreen Ayesha', 'Bibinoreen.Ayesha@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'HYDERABAD', TRUE),
  ('SOURABH_NANDAKISHORESHARMA', 'Sourabh Nandakishore Sharma', 'Sourabh.NandakishoreSharma@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'HYDERABAD', TRUE),
  ('SANDEEP_MANDA', 'Sandeep Manda', 'Sandeep.Manda@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', FALSE),
  ('VIVEK_CHATURVEDI', 'Vivek Chaturvedi', 'Vivek.Chaturvedi@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('NARASIMHA_KOPPULA', 'Narasimha Koppula', 'Narasimha.Koppula@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('VISHAL_KULKARNI', 'Vishal Kulkarni', 'Vishal.Kulkarni@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'HYDERABAD', TRUE),
  ('NILAY_GUPTA', 'Nilay Gupta', 'Nilay.Gupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'HYDERABAD', TRUE),
  ('PUJA_GANGULI', 'Puja Ganguli', 'Puja.Ganguli@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('JIT_ROYCHOWDHURY', 'Jit Roy Chowdhury', 'Jit.RoyChowdhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHISHEK_DAS', 'Abhishek Das', 'Abhishek.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARUNAVA_CHAKRABORTY', 'Arunava Chakraborty', 'Arunava.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('GARGI_DAS', 'Gargi Das', 'Gargi.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHIRUP_MUKHERJEE', 'Abhirup Mukherjee', 'Abhirup.Mukherjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANANDITA_DASGUPTA', 'Anandita Dasgupta', 'Anandita.Dasgupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARINDAM_GHOSH', 'Arindam Ghosh', 'Arindam.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUSOBHAN_DAS', 'Susobhan Das', 'Susobhan.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MANASKUMAR_CHAND', 'Manas Kumar Chand', 'ManasKumar.Chand@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('NILOTPAL_MAHADANI', 'Nilotpal Mahadani', 'Nilotpal.Mahadani@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANUJIT_GANGULY', 'Anujit Ganguly', 'Anujit.Ganguly@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KUMAR_GAURAV', 'Kumar Gaurav', 'Kumar.Gaurav@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMYA_SIKDER', 'Soumya Sikder', 'Soumya.Sikder@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MOUMITA_PRADHAN', 'Moumita Pradhan', 'Moumita.Pradhan@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANKITA_GANGULI', 'Ankita Ganguli', 'Ankita.Ganguli@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAKESH_SHUKLA', 'Rakesh Shukla', 'Rakesh.Shukla@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MINAKSHI_MITRAKUNDU', 'Minakshi Mitra Kundu', 'Minakshi.MitraKundu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRATEEK_JALAN', 'Prateek Jalan', 'Prateek.Jalan@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUCHISMITA_GOSWAMI', 'Suchismita Goswami', 'Suchismita.Goswami@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AVIK_PAL', 'Avik Pal', 'Avik.Pal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHAMIK_GHOSH', 'Shamik Ghosh', 'Shamik.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOURAV_GANGULY', 'Sourav Ganguly', 'Sourav.Ganguly@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYANTAN_SARKAR', 'Sayantan Sarkar', 'Sayantan.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHEKHAR_GUPTA', 'Shekhar Gupta', 'Shekhar.Gupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHUBHENDU_GANGULY', 'Shubhendu Ganguly', 'Shubhendu.Ganguly@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('UTSAV_SAHA', 'Utsav Saha', 'Utsav.Saha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUBHANKAR_MUKHERJEE', 'Subhankar Mukherjee', 'Subhankar.Mukherjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHIVESH_KUMAR', 'Shivesh Kumar', 'Shivesh.Kumar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SREEMOYEE_CHOWDHURY', 'Sreemoyee Chowdhury', 'Sreemoyee.Chowdhury@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('PRAKRUTA_BEHERA', 'Prakruta Behera', 'Prakruta.Behera@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SURAJIT_BASU', 'Surajit Basu', 'Surajit.Basu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBJIT_ROY', 'Debjit Roy', 'Debjit.Roy@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SWARNAPRABHA_GHOSH', 'Swarnaprabha Ghosh', 'Swarnaprabha.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PALLAVI_KARMAKAR', 'Pallavi Karmakar', 'Pallavi.Karmakar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KAUSTAV_CHANDA', 'Kaustav Chanda', 'Kaustav.Chanda@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARITRA_SURROY', 'Aritra Sur Roy', 'Aritra.SurRoy@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SAMANWAY_GHATAK', 'Samanway Ghatak', 'Samanway.Ghatak@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ANUBRATA_SANTRA', 'Anubrata Santra', 'Anubrata.Santra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOMBUDDHA_CHATTERJEE', 'Sombuddha Chatterjee', 'Sombuddha.Chatterjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('TULIKA_CHOWDHURY', 'Tulika Chowdhury', 'Tulika.Chowdhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('NILOTPAL_MUKHERJEE', 'Nilotpal Mukherjee', 'Nilotpal.Mukherjee@hyland.com', 'Services Delivery', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('SAYANDEEP_MONDAL', 'Sayandeep Mondal', 'Sayandeep.Mondal@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'KOLKATA', TRUE),
  ('POUSHALI_CHAKRABORTY', 'Poushali Chakraborty', 'Poushali.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRASID_BASU', 'Prasid Basu', 'Prasid.Basu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAIKAT_ROY', 'Saikat Roy', 'Saikat.Roy@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('TANMOY_GHOSH', 'Tanmoy Ghosh', 'Tanmoy.Ghosh@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOUMYARKA_GHOSH', 'Soumyarka Ghosh', 'Soumyarka.Ghosh@hyland.com', 'Services Delivery', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('ADITYA_NANDY', 'Aditya Nandy', 'Aditya.Nandy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUBHADEEP_BANERJEE', 'Subhadeep Banerjee', 'Subhadeep.Banerjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SWARNAJIT_ADHIKARY', 'Swarnajit Adhikary', 'Swarnajit.Adhikary@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAHUL_ROY', 'Rahul Roy', 'Rahul.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUSHOVAN_DAS', 'Sushovan Das', 'Sushovan.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAURABH_GHOSH', 'Saurabh Ghosh', 'Saurabh.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SYEDKAMALAHMED_HIRON', 'Syed Kamal Ahmed Hiron', 'SyedKamalAhmed.Hiron@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KAMALIKA_CHANDA', 'Kamalika Chanda', 'Kamalika.Chanda@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRASENJIT_ROY', 'Prasenjit Roy', 'Prasenjit.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AMIT_GUPTA', 'Amit Gupta', 'Amit.Gupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PROSENJIT_KAR', 'Prosenjit Kar', 'Prosenjit.Kar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AVIJOY_DAS', 'Avijoy Das', 'Avijoy.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SONALI_CHAKRABORTY', 'Sonali Chakraborty', 'Sonali.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AVIJIT_MITRA', 'Avijit Mitra', 'Avijit.Mitra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUMIT_PAUL', 'Sumit Paul', 'Sumit.Paul@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('APRATARKYA_BANDYOPADHAYAY', 'Apratarkya Bandyopadhayay', 'Apratarkya.Bandyopadhayay@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SWARNAVA_SADHUKHAN', 'Swarnava Sadhukhan', 'Swarnava.Sadhukhan@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SHREYASHI_CHOUDHURI', 'Shreyashi Choudhuri', 'Shreyashi.Choudhuri@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DIPANKAR_SEN', 'Dipankar Sen', 'Dipankar.Sen@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('TRISHA_SAHA', 'Trisha Saha', 'Trisha.Saha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRABAL_SRIVASTAVA', 'Prabal Srivastava', 'Prabal.Srivastava@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('RAHUL_DEY', 'Rahul Dey', 'Rahul.Dey@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMYADIP_SEN', 'Soumyadip Sen', 'Soumyadip.Sen@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEEPANJAN_GHOSH', 'Deepanjan Ghosh', 'Deepanjan.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMADIPTO_SARKAR', 'Soumadipto Sarkar', 'Soumadipto.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DHRITIDIPTA_ROY', 'Dhritidipta Roy', 'Dhritidipta.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SABARNA_GHOSH', 'Sabarna Ghosh', 'Sabarna.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARITRI_HORE', 'Aritri Hore', 'Aritri.Hore@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARGHYADEEP_BHUNIA', 'Arghyadeep Bhunia', 'Arghyadeep.Bhunia@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MILAN_SK', 'Milan Sk', 'Milan.Sk@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('VIVEK_PAI2', 'zVivek Pai', 'Vivek.Pai2@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('DEBASISH_BHUNIA', 'Debasish Bhunia', 'Debasish.Bhunia@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ADITYA_CHAKRABORTY', 'Aditya Chakraborty', 'Aditya.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARPITA_PALCHAUDHURI', 'Arpita Pal Chaudhuri', 'Arpita.Palchaudhuri@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUVAJIT_DAS', 'Suvajit Das', 'Suvajit.Das@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('CHANDRIKA_SINGH', 'Chandrika Singh', 'Chandrika.Singh@hyland.com', 'Strategic Sourcing', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('DONA_MUKHERJEE', 'Dona Mukherjee', 'Dona.Mukherjee@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMYAJIT_CHAKRABORTY', 'Soumyajit Chakraborty', 'Soumyajit.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHRESHTHA_BHATTACHARYYA', 'Shreshtha Bhattacharyya', 'Shreshtha.Bhattacharyya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('BIBHOR_JHA', 'Bibhor Jha', 'Bibhor.Jha@hyland.com', 'Global Cloud Services', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('SUBHAROOP_GHOSH', 'Subharoop Ghosh', 'Subharoop.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('INDRAJIT_SEN', 'Indrajit Sen', 'Indrajit.Sen@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AMLAN_SENGUPTA', 'Amlan Sengupta', 'Amlan.Sengupta@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('JYOTSNA_KHETPAL', 'Jyotsna Khetpal', 'Jyotsna.Khetpal@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('NAMRATA_SEAL', 'Namrata Seal', 'Namrata.Seal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('TUHIN_DEY', 'Tuhin Dey', 'Tuhin.Dey@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARKA_DE', 'Arka De', 'Arka.De@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAKESH_SHARMA', 'Rakesh Sharma', 'Rakesh.Sharma@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUBHAJIT_MAJI', 'Subhajit Maji', 'Subhajit.Maji@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOMNATH_NAYEK', 'Somnath Nayek', 'Somnath.Nayek@hyland.com', 'Global Cloud Services', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('RAHUL_RAMAN', 'Rahul Raman', 'Rahul.Raman@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ARUNAVA_PAL', 'Arunava Pal', 'Arunava.Pal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ARNAB_GOSWAMI', 'Arnab Goswami', 'Arnab.Goswami@hyland.com', 'Strategic Sourcing', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('SAKSHI_SHRIYA', 'Sakshi Shriya', 'Sakshi.Shriya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RUPSA_MANNA', 'Rupsa Manna', 'Rupsa.Manna@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHREYA_NATH', 'Shreya Nath', 'Shreya.Nath@hyland.com', 'Strategic Sourcing', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('KUMAR_SHIVAM', 'Kumar Shivam', 'Kumar.Shivam@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('NABANITA_PAUL', 'Nabanita Paul', 'Nabanita.Paul@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ADRISH_BHATTACHARYA', 'Adrish Bhattacharya', 'Adrish.Bhattacharya@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('BITAN_DAS', 'Bitan Das', 'Bitan.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ARITRA_BANERJEE', 'Aritra Banerjee', 'Aritra.Banerjee@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('KHUSHBU_SAW', 'Khushbu Saw', 'Khushbu.Saw@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SALMAN_ANSARI', 'Salman Ansari', 'Salman.Ansari@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAITEJ_BALLAV', 'Saitej Ballav', 'Saitej.Ballav@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('KANISHKA_CHOUDHURY', 'Kanishka Choudhury', 'Kanishka.Choudhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SREEJIT_ROYCHOWDHURY', 'Sreejit Roychowdhury', 'Sreejit.Roychowdhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBASMITA_MONDAL', 'Debasmita Mondal', 'Debasmita.Mondal@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('SOURAV_SEN', 'Sourav Sen', 'Sourav.Sen@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('PRADIPTO_MAJUMDAR', 'Pradipto Majumdar', 'Pradipto.Majumdar@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SUBHAHU_JAIN', 'Subhahu Jain', 'Subhahu.Jain@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('PRITHWIRAJ_MUKHERJEE', 'Prithwiraj Mukherjee', 'Prithwiraj.Mukherjee@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('GOUTAM_BOSE', 'Goutam Bose', 'Goutam.Bose@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('GOUTAM_SARKAR', 'Goutam Sarkar', 'Goutam.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARJUN_DASGUPTA', 'Arjun Dasgupta', 'Arjun.Dasgupta@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('RBHATTACHARJEE', 'Richik Bhattacharjee', 'rbhattacharjee@lawlogix.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ARKOPROBHO_PAL', 'Arkoprobho Pal', 'Arkoprobho.Pal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('GOURANGO_GHOSH', 'Gourango Ghosh', 'Gourango.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SAYAK_BISWAS', 'Sayak Biswas', 'Sayak.Biswas@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ANKIT_SAHA', 'Ankit Saha', 'Ankit.Saha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('RAJDEEP_DINDA', 'Rajdeep Dinda', 'Rajdeep.Dinda@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOUVANIK_DAS', 'Souvanik Das', 'Souvanik.Das@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SAIKAT_DUTTA', 'Saikat Dutta', 'Saikat.Dutta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MAYURA_JAGDALE', 'Mayura Jagdale', 'Mayura.Jagdale@hyland.com', 'Global Services', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('KINGSHUK_SARKAR', 'Kingshuk Sarkar', 'Kingshuk.Sarkar@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SUDATTA_RAY', 'Sudatta Ray', 'Sudatta.Ray@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RUSHALI_RATHORE', 'Rushali Rathore', 'Rushali.Rathore@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ALISHA_GUPTA', 'Alisha Gupta', 'Alisha.Gupta@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOUMYA_GANGULY', 'Soumya Ganguly', 'Soumya.Ganguly@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('PRALAY_SAHA', 'Pralay Saha', 'Pralay.Saha@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('DEBARSHI_MITRA', 'Debarshi Mitra', 'Debarshi.Mitra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAJDIPTA_BISWAS', 'Rajdipta Biswas', 'Rajdipta.Biswas@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMIK_BASU', 'Soumik Basu', 'Soumik.Basu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYANTAN_BISWAS', 'Sayantan Biswas', 'Sayantan.Biswas@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MEKHALA_SENGUPTA', 'Mekhala Sengupta', 'Mekhala.Sengupta@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AKSHAY_VALLAKATI', 'Akshay Vallakati', 'Akshay.Vallakati@hyland.com', 'Global Cloud Services', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('SHREERAM_KRISHNAJEE', 'Shreeram Krishnajee', 'Shreeram.Krishnajee@hyland.com', 'Global Cloud Services', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('SUTANU_PAUL', 'Sutanu Paul', 'Sutanu.Paul@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MANISH_SINGH', 'Manish Singh', 'Manish.Singh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DIPANKAR_SAHA', 'Dipankar Saha', 'Dipankar.Saha@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('KAMALENDU_BAIDYA', 'Kamalendu Baidya', 'Kamalendu.Baidya@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AMIT_HANSDA', 'Amit Hansda', 'Amit.Hansda@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('POOJA_SHAW', 'Pooja Shaw', 'Pooja.Shaw@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOUMEN_CHATTERJEE', 'Soumen Chatterjee', 'Soumen.Chatterjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHIRUP_DAS', 'Abhirup Das', 'Abhirup.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SNEHARGHYA_PATHAK', 'Sneharghya Pathak', 'Sneharghya.Pathak@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOUMYAKANTI_CHAKRABORTY', 'Soumyakanti Chakraborty', 'Soumyakanti.Chakraborty@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('NILANJAN_SEN', 'Nilanjan Sen', 'Nilanjan.Sen@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MONALISA_CHANDRA', 'Monalisa Chandra', 'Monalisa.Chandra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHISHEK_BANERJEE', 'Abhishek Banerjee', 'Abhishek.Banerjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEEPJIT_DAS', 'Deepjit Das', 'Deepjit.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRADEEP_MUKHERJEE', 'Pradeep Mukherjee', 'Pradeep.Mukherjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('BIDISHA_KUNDU', 'Bidisha Kundu', 'Bidisha.Kundu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANISH_CHAKRABORTY', 'Anish Chakraborty', 'Anish.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KUMARSREYAM_NANDI', 'Kumarsreyam Nandi', 'Kumarsreyam.Nandi@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANKITA_DAS', 'Ankita Das', 'Ankita.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ASHESH_CHAKRABORTY', 'Ashesh Chakraborty', 'Ashesh.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DUTTA_ARNAB', 'Dutta Arnab', 'Dutta.Arnab@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAPTARSHI_GHOSH', 'Saptarshi Ghosh', 'Saptarshi.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KRITI_KHATTAR', 'Kriti Khattar', 'Kriti.Khattar@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOUVIK_SEN', 'Souvik Sen', 'Souvik.Sen@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AMBRIT_PATNAIK', 'Ambrit Patnaik', 'Ambrit.Patnaik@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('DEBROOP_SENGUPTA', 'Debroop Sengupta', 'Debroop.Sengupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARUNABHA_BERA', 'Arunabha Bera', 'Arunabha.Bera@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('KAR_SOUMYA', 'Kar Soumya', 'Kar.Soumya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MALLINATH_BASU', 'Mallinath Basu', 'Mallinath.Basu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('NIMITTA_GANGULI', 'Nimitta Ganguli', 'Nimitta.Ganguli@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SANDIP_MANPURIA', 'Sandip Manpuria', 'Sandip.Manpuria@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('NIRAJ_PANDEY', 'Niraj Pandey', 'Niraj.Pandey@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RITTIK_JANA', 'Rittik Jana', 'Rittik.Jana@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SANJOY_DAS', 'Sanjoy Das', 'Sanjoy.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('BHARGABI_NANDA', 'Bhargabi Nanda', 'Bhargabi.Nanda@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMYA_KAR', 'Soumya Kar', 'Soumya.Kar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('NEHA_SUBHANJE', 'Neha Subhanje', 'Neha.Subhanje@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('MUNESH_AGARWAL', 'Munesh Agarwal', 'Munesh.Agarwal@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARINDAM_DATTA', 'Arindam Datta', 'Arindam.Datta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ROHIT_MONDAL', 'Rohit Mondal', 'Rohit.Mondal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYAN_CHATTERJEE', 'Sayan Chatterjee', 'Sayan.Chatterjee@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('ASHISH_GUPTA', 'Ashish Gupta', 'Ashish.Gupta@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('BAISHALI_BANDYOPADHYAY', 'Baishali Bandyopadhyay', 'Baishali.Bandyopadhyay@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DIPTI_KACHHAP', 'Dipti Kachhap', 'Dipti.Kachhap@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('MAMUN_ARFIN', 'Mamun Arfin', 'Mamun.Arfin@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ARNAB_DUTTA', 'Arnab Dutta', 'Arnab.Dutta@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ISA_ALI', 'Isa Ali', 'Isa.Ali@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARNAB_MULLICK', 'Arnab Mullick', 'Arnab.Mullick@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SANDIP_MANDAL', 'Sandip Mandal', 'Sandip.Mandal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AMIT_CHAKRABORTY', 'Amit Chakraborty', 'Amit.Chakraborty@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('PROTICK_SARKAR', 'Protick Sarkar', 'Protick.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYANTANI_PODDER', 'Sayantani Podder', 'Sayantani.Podder@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DIPANJAN_MUKHERJEE', 'Dipanjan Mukherjee', 'Dipanjan.Mukherjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEVJIT_SARKAR', 'Devjit Sarkar', 'Devjit.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SHIVANGI_SHREE', 'Shivangi Shree', 'Shivangi.Shree@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AVIJIT_GHOSH', 'Avijit Ghosh', 'Avijit.Ghosh@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('TRIPTI_DAS', 'Tripti Das', 'Tripti.Das@hyland.com', 'Global Services', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('EKATA_DASGUPTA', 'Ekata Dasgupta', 'Ekata.Dasgupta@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOMNATH_SENGUPTA', 'Somnath Sengupta', 'Somnath.Sengupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOURODEEP_ROY', 'Sourodeep Roy', 'Sourodeep.Roy@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('POLI_PAUL', 'Poli Paul', 'Poli.Paul@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYANTAK_KARAR', 'Sayantak Karar', 'Sayantak.Karar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOUMABRATA_BHATTACHARYA', 'Soumabrata Bhattacharya', 'Soumabrata.Bhattacharya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUGATA_DAS', 'Sougata Das', 'Sougata.Das@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SAMBARAN_MAITY', 'Sambaran Maity', 'Sambaran.Maity@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUVIK_SAMANTA', 'Souvik Samanta', 'Souvik.Samanta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHRA_PODDAR', 'Abhra Poddar', 'Abhra.Poddar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RIDDHISATTWA_BHATTACHARYA', 'Riddhisattwa bhattacharya', 'Riddhisattwa.bhattacharya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('NEERAJ_JHA', 'Neeraj Jha', 'Neeraj.Jha@hyland.com', 'Global Cloud Services', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('SREYA_SARKAR', 'Sreya Sarkar', 'Sreya.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ADITYA_SARAF', 'Aditya Saraf', 'Aditya.Saraf@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ARNAB_SAHA', 'Arnab Saha', 'Arnab.Saha@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('ARIJIT_MUKHERJEE', 'Arijit Mukherjee', 'Arijit.Mukherjee@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMYAKANTI_GHOSH', 'Soumya Kanti Ghosh', 'SoumyaKanti.Ghosh@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SUPRITI_PAUL', 'Supriti Paul', 'Supriti.Paul@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARPAN_MUKHERJEE', 'Arpan Mukherjee', 'Arpan.Mukherjee@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('ABHISHEK_NANDI', 'Abhishek Nandi', 'Abhishek.Nandi@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('JATIN_KESHARWANI', 'Jatin Kesharwani', 'Jatin.Kesharwani@hyland.com', 'Strategic Sourcing', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('NEELLOHIT_BOSE', 'Neellohit Bose', 'Neellohit.Bose@hyland.com', 'Strategic Sourcing', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('SAMBIT_ROUT', 'Sambit Rout', 'Sambit.Rout@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHISHIKTA_GUPTA', 'Abhishikta Gupta', 'Abhishikta.Gupta@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AMIT_DUTTAROY', 'Amit Duttaroy', 'Amit.Duttaroy@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('ABHRAJYOTI_KUNDU', 'Abhrajyoti Kundu', 'Abhrajyoti.Kundu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RUDRA_MALHOTRA', 'Rudra Malhotra', 'Rudra.Malhotra@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('INDRANIL_MAITI', 'Indranil Maiti', 'Indranil.Maiti@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAUVIK_GHOSH', 'Sauvik Ghosh', 'Sauvik.Ghosh@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SRIRAM_KETHA', 'Sriram Ketha', 'Sriram.Ketha@hyland.com', 'Global Cloud Services', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('SAPTADIPA_ROY', 'Saptadipa Roy', 'Saptadipa.Roy@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('RISHAV_MITRA', 'Rishav Mitra', 'Rishav.Mitra@hyland.com', 'Strategic Sourcing', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('INDRAYAN_GANGULY', 'Indrayan Ganguly', 'Indrayan.Ganguly@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANKIT_KAMDAR', 'Ankit Kamdar', 'Ankit.Kamdar@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYANTAN_GHOSHDASTIDER', 'Sayantan Ghoshdastider', 'Sayantan.Ghoshdastider@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('HARSH_CHAURASIA', 'Harsh Chaurasia', 'Harsh.Chaurasia@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SRIMANTA_SINGH', 'Srimanta Singh', 'Srimanta.Singh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUGATA_MAITRA', 'Sougata Maitra', 'Sougata.Maitra@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SESHADRI_SHOMECHOWDHURI', 'Seshadri Shome Chowdhuri', 'Seshadri.ShomeChowdhuri@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KRISHNENDU_DEBNATH', 'Krishnendu Debnath', 'Krishnendu.Debnath@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('KESHAV_SHARMA', 'Keshav Sharma', 'Keshav.Sharma@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'KOLKATA', FALSE),
  ('SAYAN_MITRA', 'Sayan Mitra', 'Sayan.Mitra@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SUBHAJIT_CHAKRABORTTY', 'Subhajit Chakrabortty', 'Subhajit.Chakrabortty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AVIJIT_DUTTA', 'Avijit Dutta', 'Avijit.Dutta@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ALOLIKA_GHOSH', 'Alolika Ghosh', 'Alolika.Ghosh@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'KOLKATA', FALSE),
  ('NIHA_AGARWAL', 'Niha Agarwal', 'Niha.Agarwal@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('SWARNENDU_PAUL', 'Swarnendu Paul', 'Swarnendu.Paul@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOHAM_SARKAR', 'Soham Sarkar', 'Soham.Sarkar@hyland.com', 'Customer Operations', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHIRUP_CHAKRABORTY', 'Abhirup Chakraborty', 'Abhirup.Chakraborty@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('DEBAPAM_DAS', 'Debapam Das', 'Debapam.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('VADANSH_KULSHRESHTHA', 'Vadansh Kulshreshtha', 'Vadansh.Kulshreshtha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('INDRAJIT_DAN', 'Indrajit Dan', 'Indrajit.Dan@hyland.com', 'Global Services', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('BHASKAR_GHOSHDASTIDAR', 'Bhaskar Ghosh Dastidar', 'Bhaskar.GhoshDastidar@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('RAHUL_KAPOOR', 'Rahul Kapoor', 'Rahul.Kapoor@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('PRASANTA_BANERJEE', 'Prasanta Banerjee', 'Prasanta.Banerjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARINDAM_MONDAL', 'Arindam Mondal', 'Arindam.Mondal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ROSHAN_DHAR', 'Roshan Dhar', 'Roshan.Dhar@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('LAHARI_BASU', 'Lahari Basu', 'Lahari.Basu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHAHNAWAZ_HAQUE', 'Shahnawaz Haque', 'Shahnawaz.Haque@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KHUSHI_SINGH', 'Khushi Singh', 'Khushi.Singh@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SUBHADEEP_BHAUMIK', 'Subhadeep Bhaumik', 'Subhadeep.Bhaumik@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('ASIT_DE', 'Asit De', 'Asit.De@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RUPA_GANGULY', 'Rupa Ganguly', 'Rupa.Ganguly@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'KOLKATA', FALSE),
  ('ANKITA_DUTTA', 'Ankita Dutta', 'Ankita.Dutta@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'KOLKATA', FALSE),
  ('SAGNIK_CHOWDHURY', 'Sagnik Chowdhury', 'Sagnik.Chowdhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAMRAT_DUTTA', 'Samrat Dutta', 'Samrat.Dutta@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SWAGATAM_BOSE', 'Swagatam Bose', 'Swagatam.Bose@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANGSUKA_CHAKRABORTY', 'Angsuka Chakraborty', 'Angsuka.Chakraborty@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'KOLKATA', TRUE),
  ('MILAN_MUKHERJEE', 'Milan Mukherjee', 'Milan.Mukherjee@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SHOUVIK_CHATTERJEE', 'Shouvik Chatterjee', 'Shouvik.Chatterjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KUMARI_SWASTI', 'Kumari Swasti', 'Kumari.Swasti@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMYADIP_BASUMALLIK', 'Soumyadip Basumallik', 'Soumyadip.Basumallik@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SAMIKSHA_ACHARYA', 'Samiksha Acharya', 'Samiksha.Acharya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYANTAN_SENGUPTA', 'Sayantan Sengupta', 'Sayantan.Sengupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('GOURAB_ROY', 'Gourab Roy', 'Gourab.Roy@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHIRUP_SINHA', 'Abhirup Sinha', 'Abhirup.Sinha@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('ANWESHA_DUTTA', 'Anwesha Dutta', 'Anwesha.Dutta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUMANTA_MONDAL', 'Sumanta Mondal', 'Sumanta.Mondal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOURAV_BANERJEE', 'Sourav Banerjee', 'Sourav.Banerjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANNESHA_BHATTACHARJEE', 'Annesha Bhattacharjee', 'Annesha.Bhattacharjee@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOUMI_GUHA', 'Soumi Guha', 'Soumi.Guha@hyland.com', 'Global Cloud Services', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SANKHADEEP_BISWAS', 'Sankhadeep Biswas', 'Sankhadeep.Biswas@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUSHMITA_GOSWAMI', 'Sushmita Goswami', 'Sushmita.Goswami@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('CHANDAN_SHARMA', 'Chandan Sharma', 'Chandan.Sharma@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AVINASH_TIWARI', 'Avinash Tiwari', 'Avinash.Tiwari@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOUMYA_GUHA', 'Soumya Guha', 'Soumya.Guha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MILIND_AGARWAL', 'Milind Agarwal', 'Milind.Agarwal@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SARMISTHA_SADHUKHAN', 'Sarmistha Sadhukhan', 'Sarmistha.Sadhukhan@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('PRITHA_BHATTACHARYA', 'Pritha Bhattacharya', 'Pritha.Bhattacharya@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('TIRTHA_CHOUDHURY', 'Tirtha Choudhury', 'Tirtha.Choudhury@hyland.com', 'Facilities', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('MAYUR_BANDYOPADHYAY', 'Mayur Bandyopadhyay', 'Mayur.Bandyopadhyay@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUDIPTO_SARKAR', 'Sudipto Sarkar', 'Sudipto.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARNAB_PAL', 'Arnab Pal', 'Arnab.Pal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SANDIPAN_JANA', 'Sandipan Jana', 'Sandipan.Jana@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUMANT_KUMAR', 'Sumant Kumar', 'Sumant.Kumar@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBABRATA_MANDAL', 'Debabrata Mandal', 'Debabrata.Mandal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ROHIT_JADAV', 'Rohit Jadav', 'Rohit.Jadav@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('MANAS_LAHA', 'Manas Laha', 'Manas.Laha@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MRITTIKA_DEBNATH', 'Mrittika Debnath', 'Mrittika.Debnath@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUGATA_MITRA', 'Sougata Mitra', 'Sougata.Mitra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RITAM_GHOSH', 'Ritam Ghosh', 'Ritam.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('TUNIR_ADHIKARY', 'Tunir Adhikary', 'Tunir.Adhikary@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBARUN_SAHA', 'Debarun Saha', 'Debarun.Saha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KASHISH_ROY', 'Kashish Roy', 'Kashish.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SASIKAR_KOMMERA', 'Sasikar Kommera', 'Sasikar.Kommera@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('YASH_GUPTA', 'Yash Gupta', 'Yash.Gupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAKSHI_GUPTA', 'Sakshi Gupta', 'Sakshi.Gupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KUMAR_SHUBHAM', 'Kumar Shubham', 'Kumar.Shubham@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAUMIT_MANDAL', 'Saumit Mandal', 'Saumit.Mandal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAUGATA_SARKAR', 'Saugata Sarkar', 'Saugata.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('KOUSHIK_DAS', 'Koushik Das', 'Koushik.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('GRETA_GHOSH', 'Greta Ghosh', 'Greta.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARINDAM_PAL', 'Arindam Pal', 'Arindam.Pal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYAN_CHAKRABORTY', 'Sayan Chakraborty', 'Sayan.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARINDAM_CHAKRABARTI', 'Arindam Chakrabarti', 'Arindam.Chakrabarti@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('SANKALAN_SARKER', 'Sankalan Sarker', 'Sankalan.Sarker@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('DEBOJIT_KUNDU', 'Debojit Kundu', 'Debojit.Kundu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARJUN_SEN', 'Arjun Sen', 'Arjun.Sen@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DIPANKAR_DAS', 'Dipankar Das', 'Dipankar.Das@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('NISHANT_KUMAR', 'Nishant Kumar', 'Nishant.Kumar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARITRA_GUHA', 'Aritra Guha', 'Aritra.Guha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUDIP_MANPURIA', 'Sudip Manpuria', 'Sudip.Manpuria@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('UTTAMPRIYAA_BASU', 'Uttampriyaa Basu', 'Uttampriyaa.Basu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ROOSHABH_SHETH', 'Rooshabh Sheth', 'Rooshabh.Sheth@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('BIRAJBHUSHAN_CHOUDHURY', 'Biraj Bhushan Choudhury', 'BirajBhushan.Choudhury@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('ANITA_GUHA', 'Anita Guha', 'Anita.Guha@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('CHIRADEEP_BANERJEE', 'Chiradeep Banerjee', 'Chiradeep.Banerjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PULAK_PAUL', 'Pulak Paul', 'Pulak.Paul@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUBHASMITA_NANDA', 'Subhasmita Nanda', 'Subhasmita.Nanda@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUBHODIP_KUMAR', 'Subhodip Kumar', 'Subhodip.Kumar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PROSUNE_BOSE', 'Prosune Bose', 'Prosune.Bose@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRASENJIT_PAUL', 'Prasenjit Paul', 'Prasenjit.Paul@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MITHUN_KUNDU', 'Mithun Kundu', 'Mithun.Kundu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAGNIK_MAJUMDER', 'Sagnik Majumder', 'Sagnik.Majumder@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KIRAN_NALLAMALA', 'Kiran Nallamala', 'Kiran.Nallamala@hyland.com', 'Global Cloud Services', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('SUBARNA_MAZUMDAR', 'Subarna Mazumdar', 'Subarna.Mazumdar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('VICTOR_MUKHERJEE', 'Victor Mukherjee', 'Victor.Mukherjee@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('KAUSTAV_CHAKRABORTY', 'Kaustav Chakraborty', 'Kaustav.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBOJYOTI_RAY', 'Debojyoti Ray', 'Debojyoti.Ray@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SKJAHANGIR_KABIR', 'Sk Jahangir Kabir', 'SkJahangir.Kabir@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANIRUDDHA_DAS', 'Aniruddha Das', 'Aniruddha.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ROHAN_GHOSH', 'Rohan Ghosh', 'Rohan.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARUNIMA_CHATTERJEE', 'Arunima Chatterjee', 'Arunima.Chatterjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SANTU_DHARA', 'Santu Dhara', 'Santu.Dhara@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAMBIT_SARKAR', 'Sambit Sarkar', 'Sambit.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('VIKRANT_CHOPRA', 'Vikrant Chopra', 'Vikrant.Chopra@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', FALSE),
  ('PARTHA_BASAK', 'Partha Basak', 'Partha.Basak@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBASUBHRA_DEY', 'Debasubhra Dey', 'Debasubhra.Dey@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUPRATIK_DEBNATH', 'Supratik Debnath', 'Supratik.Debnath@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUNANDA_ROY', 'Sunanda Roy', 'Sunanda.Roy@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOURAV_DAS', 'Sourav Das', 'Sourav.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('JOY_BANERJEE', 'Joy Banerjee', 'Joy.Banerjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('NITISH_BHATTACHARJEE', 'Nitish Bhattacharjee', 'Nitish.Bhattacharjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AYAN_MITRA', 'Ayan Mitra', 'Ayan.Mitra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUVIK_SENGUPTA', 'Souvik Sengupta', 'Souvik.Sengupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KOUSIK_PAL', 'Kousik Pal', 'Kousik.Pal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARPAN_BANDYOPADHYAY', 'Arpan Bandyopadhyay', 'Arpan.Bandyopadhyay@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SURANJANA_BHOWMICK', 'Suranjana Bhowmick', 'Suranjana.Bhowmick@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBAJYOTI_SIKDAR', 'Debajyoti Sikdar', 'Debajyoti.Sikdar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHIB_PAL', 'Shib Pal', 'Shib.Pal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('KUSHAL_BANIK', 'Kushal Banik', 'Kushal.Banik@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBDUT_ROY', 'Debdut Roy', 'Debdut.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANNESH_SAMANTA', 'Annesh Samanta', 'Annesh.Samanta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RONAK_MAJUMDER', 'Ronak Majumder', 'Ronak.Majumder@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHUBHAJIT_ROY', 'Shubhajit Roy', 'Shubhajit.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('GAURAV_AGRAWAL', 'Gaurav Agrawal', 'Gaurav.Agrawal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('MOZAMMIL_ATHAR', 'Mozammil Athar', 'Mozammil.Athar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANIRBAN_ROY', 'Anirban Roy', 'Anirban.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SANCHARI_GHOSH', 'Sanchari Ghosh', 'Sanchari.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MAHIKA_SINHA', 'Mahika Sinha', 'Mahika.Sinha@hyland.com', 'Global Services', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('KOUSHIK_CHOWDHURY', 'Koushik Chowdhury', 'Koushik.Chowdhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('CHANDRAGUPTA_MISHRA', 'Chandragupta Mishra', 'Chandragupta.Mishra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('NEELABHRA_BHATTACHARYYA', 'Neelabhra Bhattacharyya', 'Neelabhra.Bhattacharyya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('TIRTHANKAR_BOSE', 'Tirthankar Bose', 'Tirthankar.Bose@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MUKHERJEE_ARIJIT', 'Mukherjee Arijit', 'Mukherjee.Arijit@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAPTAK_BAGCHI', 'Saptak Bagchi', 'Saptak.Bagchi@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOURJYA_MUKHERJEE', 'Sourjya Mukherjee', 'Sourjya.Mukherjee@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('VAIBHAV_MEHTA', 'Vaibhav Mehta', 'Vaibhav.Mehta@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ARITRA_BANERJEE2', 'Aritra Banerjee2', 'Aritra.Banerjee2@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMYAJIT_DATTA', 'Soumyajit Datta', 'Soumyajit.Datta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('JAYESH_SHAW', 'Jayesh Shaw', 'Jayesh.Shaw@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOUMIK_MUKHERJEE', 'Soumik Mukherjee', 'Soumik.Mukherjee@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AUROBINDA_MAHAPATRA', 'Aurobinda Mahapatra', 'Aurobinda.Mahapatra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOURAV_MAJUMDER', 'Sourav Majumder', 'Sourav.Majumder@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AMAN_TRIPATHI', 'Aman Tripathi', 'Aman.Tripathi@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('VIKASH_KUMAR', 'Vikash Kumar', 'Vikash.Kumar@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SHAYANTANI_KAR', 'Shayantani Kar', 'Shayantani.Kar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHREYA_JAISWAL', 'Shreya Jaiswal', 'Shreya.Jaiswal@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBOSMITA_BHATTACHARJEE', 'Debosmita Bhattacharjee', 'Debosmita.Bhattacharjee@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('SHAONI_BOSE', 'Shaoni Bose', 'Shaoni.Bose@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SHUBHANAN_SINHARAY', 'Shubhanan Sinha Ray', 'Shubhanan.SinhaRay@hyland.com', 'Global Cloud Services', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('ARUP_DWARI', 'Arup Dwari', 'Arup.Dwari@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SHANKHA_SANYAL', 'Shankha Sanyal', 'Shankha.Sanyal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRIYA_SINGH', 'Priya Singh', 'Priya.Singh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('RAJAT_MONDAL', 'Rajat Mondal', 'Rajat.Mondal@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('CHIRAG_KESHRI', 'Chirag Keshri', 'Chirag.Keshri@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('ANINDITA_BOSE', 'Anindita Bose', 'Anindita.Bose@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PALKI_BANERJEE', 'Palki Banerjee', 'Palki.Banerjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SALONI_MARWAH', 'Saloni Marwah', 'Saloni.Marwah@hyland.com', 'Customer Success', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('MADHURIMA_DAS', 'Madhurima Das', 'Madhurima.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ADHYETA_SENAPATI', 'Adhyeta Senapati', 'Adhyeta.Senapati@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAPTAM_KARMAKAR', 'Saptam Karmakar', 'Saptam.Karmakar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMALYA_CHOUDHURY', 'Soumalya Choudhury', 'Soumalya.Choudhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RISHABH_AGARWAL', 'Rishabh Agarwal', 'Rishabh.Agarwal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBOTTAM_DAS', 'Debottam Das', 'Debottam.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRAMIT_ROY', 'Pramit Roy', 'Pramit.Roy@hyland.com', 'Customer Success', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('KINGSHUK_CHAKRABORTY', 'Kingshuk Chakraborty', 'Kingshuk.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANGSHUMAN_GHOSH', 'Angshuman Ghosh', 'Angshuman.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANKITA_PANT', 'Ankita Pant', 'Ankita.Pant@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AYUSHI_PRIYADARSHANI', 'Ayushi Priyadarshani', 'Ayushi.Priyadarshani@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('BRATI_BISWAS', 'Brati Biswas', 'Brati.Biswas@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SANJAY_VISHWAKARMA', 'Sanjay Vishwakarma', 'Sanjay.Vishwakarma@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SIVOM_SINGH', 'Sivom Singh', 'Sivom.Singh@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('SHRISTI_JAIN', 'Shristi Jain', 'Shristi.Jain@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('PRIYANJITA_BHOWMICK', 'Priyanjita Bhowmick', 'Priyanjita.Bhowmick@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('ABIRAN_CHATTERJEE', 'Abiran Chatterjee', 'Abiran.Chatterjee@hyland.com', 'Global Cloud Services', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('ANIK_DASGUPTA', 'Anik Dasgupta', 'Anik.Dasgupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUVIK_DATTA', 'Souvik Datta', 'Souvik.Datta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUMIT_BURNWAL', 'Sumit Burnwal', 'Sumit.Burnwal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AKTA_MUKIM', 'Akta Mukim', 'Akta.Mukim@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'KOLKATA', FALSE),
  ('SUBHAJIT_ROY', 'Subhajit Roy', 'Subhajit.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KUMAR_SHAILENDRAPANDA', 'Kumar Shailendra Panda', 'Kumar.ShailendraPanda@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('BIMAL_PAUL', 'Bimal Paul', 'Bimal.Paul@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('NISHANTO_SAHA', 'Nishanto Saha', 'Nishanto.Saha@hyland.com', 'Customer Success', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('ROMMEL_CHOWDHURY', 'Rommel Chowdhury', 'Rommel.Chowdhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DIPANSHU_CHANDGOTHIA', 'Dipanshu Chandgothia', 'Dipanshu.Chandgothia@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('SARBAJIT_NANDY', 'Sarbajit Nandy', 'Sarbajit.Nandy@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SAYAN_DE', 'Sayan De', 'Sayan.De@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAJKUMAR_RAJKUMAR', 'Rajkumar Rajkumar', 'Rajkumar.Rajkumar@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AMIT_CHAKRABORTI', 'Amit Chakraborti', 'Amit.Chakraborti@hyland.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOHAM_CHAKRABORTY', 'Soham Chakraborty', 'Soham.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SPANDAN_BASU', 'Spandan Basu', 'Spandan.Basu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ATREYEE_CHAKRABORTY', 'Atreyee Chakraborty', 'Atreyee.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANKIT_DHAR', 'Ankit Dhar', 'Ankit.Dhar@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('KHUSBOO_JHA', 'Khusboo Jha', 'Khusboo.Jha@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SHARMISTHA_GUHAMAJUMDAR', 'Sharmistha Guhamajumdar', 'Sharmistha.Guhamajumdar@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', FALSE),
  ('DEBANJAN_DAS', 'Debanjan Das', 'Debanjan.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SCHATTERJEE', 'Saheli Chatterjee', 'schatterjee@lawlogix.com', 'Research and Development', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('DEEP_BANERJEE', 'Deep Banerjee', 'Deep.Banerjee@hyland.com', 'Legal', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('BISWADEV_SARKAR', 'Biswadev Sarkar', 'Biswadev.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ROUNAK_ROY', 'Rounak Roy', 'Rounak.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHIVAN_CHOWDHURY', 'Shivan Chowdhury', 'Shivan.Chowdhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('TAMALIKA_CHAKRABORTY', 'Tamalika Chakraborty', 'Tamalika.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MOUSUMI_BANERJEE', 'Mousumi Banerjee', 'Mousumi.Banerjee@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUROMITA_CHATTERJEE', 'Souromita Chatterjee', 'Souromita.Chatterjee@hyland.com', 'Legal', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SUPRIYA_KUNDU', 'Supriya Kundu', 'Supriya.Kundu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUPRATIM_MITRA', 'Supratim Mitra', 'Supratim.Mitra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('NAMRATA_BASAK', 'Namrata Basak', 'Namrata.Basak@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'KOLKATA', TRUE),
  ('CHANDAN_CHATTERJEE', 'Chandan Chatterjee', 'Chandan.Chatterjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOURAV_MAJI', 'Sourav Maji', 'Sourav.Maji@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUMAN_CHATTOPADHYAY', 'Suman Chattopadhyay', 'Suman.Chattopadhyay@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PUSHPAK_BANERJEE', 'Pushpak Banerjee', 'Pushpak.Banerjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PARTHASARATHI_MAHANTI', 'Parthasarathi Mahanti', 'Parthasarathi.Mahanti@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SURYARAJ_BHADURI', 'Suryaraj Bhaduri', 'Suryaraj.Bhaduri@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHIRUP_BHATTACHARYA', 'Abhirup Bhattacharya', 'Abhirup.Bhattacharya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('TANIEA_DAS', 'Taniea Das', 'Taniea.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOHAM_BHATTACHARYA', 'Soham Bhattacharya', 'Soham.Bhattacharya@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('KUSHAL_GUHA', 'Kushal Guha', 'Kushal.Guha@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', FALSE),
  ('ANIRBAN_NATH', 'Anirban Nath', 'Anirban.Nath@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KOULIK_SARKER', 'Koulik Sarker', 'Koulik.Sarker@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAURAV_SAHA', 'Saurav Saha', 'Saurav.Saha@hyland.com', 'Human Resources', 'HR', 'HYBRID', 'KOLKATA', TRUE),
  ('PUSHKAL_GUHACHOUDHURY', 'Pushkal Guha Choudhury', 'Pushkal.GuhaChoudhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SARTHAK_DEY', 'Sarthak Dey', 'Sarthak.Dey@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SUMIT_JANA', 'Sumit Jana', 'Sumit.Jana@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOMNATH_ROY', 'Somnath Roy', 'Somnath.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PUSPENDU_MUKHERJEE', 'Puspendu Mukherjee', 'Puspendu.Mukherjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHREYA_SAHA', 'Shreya Saha', 'Shreya.Saha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARPAN_GHOSHAL', 'Arpan Ghoshal', 'Arpan.Ghoshal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUVIK_GHOSH', 'Souvik Ghosh', 'Souvik.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARUNAVA_KUNDU', 'Arunava Kundu', 'Arunava.Kundu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('INDRANIL_DAS', 'Indranil Das', 'Indranil.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUVIK_NAN', 'Souvik Nan', 'Souvik.Nan@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KHUSHI_SINGHANIA', 'Khushi Singhania', 'Khushi.Singhania@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', FALSE),
  ('RUPANJANA_GANGULY', 'Rupanjana Ganguly', 'Rupanjana.Ganguly@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYANTAN_MITRA', 'Sayantan Mitra', 'Sayantan.Mitra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PARTHASARATHI_PATRA', 'Parthasarathi Patra', 'Parthasarathi.Patra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAKESH_MOHATA', 'Rakesh Mohata', 'Rakesh.Mohata@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOURADIP_SAHA', 'Souradip Saha', 'Souradip.Saha@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('JOSH_USER', 'Josh User', 'Josh.User@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ATREYEE_PAUL', 'Atreyee Paul', 'Atreyee.Paul@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KISHALAY_BHATTACHARYA', 'Kishalay Bhattacharya', 'Kishalay.Bhattacharya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SUSMITA_SINHA', 'Susmita Sinha', 'Susmita.Sinha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRACHI_KUMARI', 'Prachi Kumari', 'Prachi.Kumari@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DABARSHI_MITRA', 'Dabarshi Mitra', 'Dabarshi.Mitra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MAJI_SOURAV', 'Maji Sourav', 'Maji.Sourav@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MADHUBANTI_ROY', 'Madhubanti Roy', 'Madhubanti.Roy@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SUBHAM_SAMANTA', 'Subham Samanta', 'Subham.Samanta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANEESH_MAZUMDER', 'Aneesh Mazumder', 'Aneesh.Mazumder@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHIBAM_SAMADDAR', 'Shibam Samaddar', 'Shibam.Samaddar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SANMITRA_BARMAN', 'Sanmitra Barman', 'Sanmitra.Barman@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RISHI_MONDAL', 'Rishi Mondal', 'Rishi.Mondal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARCHISMAN_BANIK', 'Archisman Banik', 'Archisman.Banik@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBASMITA_DASGUPTA', 'Debasmita Dasgupta', 'Debasmita.Dasgupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('BISWARUP_CHATTERJEE', 'Biswarup Chatterjee', 'Biswarup.Chatterjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DIPANJAN_GHOSH', 'Dipanjan Ghosh', 'Dipanjan.Ghosh@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('PALLAV_SANTRA', 'Pallav Santra', 'Pallav.Santra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PALASH_CHAKRABORTY', 'Palash Chakraborty', 'Palash.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('DEEPSIKHA_ROY', 'Deepsikha Roy', 'Deepsikha.Roy@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('POOJA_BANERJEE', 'Pooja Banerjee', 'Pooja.Banerjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBI_SEN', 'Debi Sen', 'Debi.Sen@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RANAJIT_HORE', 'Ranajit Hore', 'Ranajit.Hore@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AREETRA_HALDER', 'Areetra Halder', 'Areetra.Halder@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AGNIVA_CHOWDHURY', 'Agniva Chowdhury', 'Agniva.Chowdhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('TANDRITA_ROY', 'Tandrita Roy', 'Tandrita.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMYO_SINHA', 'Soumyo Sinha', 'Soumyo.Sinha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAMKRISHNA_GHOSH', 'Ramkrishna Ghosh', 'Ramkrishna.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHISHEK_RAI', 'Abhishek Rai', 'Abhishek.Rai@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('VISHAL_BOSE', 'Vishal Bose', 'Vishal.Bose@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('APOORVA_KASHYAP', 'Apoorva Kashyap', 'Apoorva.Kashyap@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUSOVAN_GHOSH', 'Susovan Ghosh', 'Susovan.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SNEHASISH_KARCHOWDHURY', 'Snehasish Kar Chowdhury', 'Snehasish.KarChowdhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBOSMITA_CHAKRABORTY', 'Debosmita Chakraborty', 'Debosmita.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABIR_DUTTA', 'Abir Dutta', 'Abir.Dutta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARPAN_PAUL', 'Arpan Paul', 'Arpan.Paul@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUPRATIK_SINHA', 'Supratik Sinha', 'Supratik.Sinha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KARAN_POUDYAL', 'Karan Poudyal', 'Karan.Poudyal@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAHUL_CHATTERJEE', 'Rahul Chatterjee', 'Rahul.Chatterjee@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SUMIT_PRAJAPATI', 'Sumit Prajapati', 'Sumit.Prajapati@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('MONIKA_CHAUHAN', 'Monika Chauhan', 'Monika.Chauhan@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('TAMISRA_SARKAR', 'Tamisra Sarkar', 'Tamisra.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHIGYAN_MAJUMDER', 'Abhigyan Majumder', 'Abhigyan.Majumder@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SWEETY_RAM', 'Sweety Ram', 'Sweety.Ram@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('BHASKAR_GAYEN', 'Bhaskar Gayen', 'Bhaskar.Gayen@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('BELAL_ANSARI', 'Belal Ansari', 'Belal.Ansari@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('GUPTA_ABHISHEK', 'Gupta Abhishek', 'Gupta.Abhishek@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUVICK_MANDAL', 'Souvick Mandal', 'Souvick.Mandal@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('KARTHIK_KOLLIPARA', 'Karthik Kollipara', 'Karthik.Kollipara@hyland.com', '', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('CHIRANTAN_DEY', 'Chirantan Dey', 'Chirantan.Dey@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('MOUSUMI_PODDER', 'Mousumi Podder', 'Mousumi.Podder@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('TIRTHANKAR_KUNDU', 'Tirthankar Kundu', 'Tirthankar.Kundu@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAURAV_TRIPATHI', 'Saurav Tripathi', 'Saurav.Tripathi@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SHREYA_SEN', 'Shreya Sen', 'Shreya.Sen@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SATYAM_SAH', 'Satyam Sah', 'Satyam.Sah@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARKO_CHATTERJEE', 'Arko Chatterjee', 'Arko.Chatterjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHISHEK_JAISWAL', 'Abhishek Jaiswal', 'Abhishek.Jaiswal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('TATHAGATA_NANDI', 'Tathagata Nandi', 'Tathagata.Nandi@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBJIT_KAR', 'Debjit Kar', 'Debjit.Kar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAHUL_CHAKRABORTY', 'Rahul Chakraborty', 'Rahul.Chakraborty@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARINDAM_ROY', 'Arindam Roy', 'Arindam.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAKESH_GHOSAL', 'Rakesh Ghosal', 'Rakesh.Ghosal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHUBHANKAR_PANDEY', 'Shubhankar Pandey', 'Shubhankar.Pandey@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KAUSHIK_HALDER', 'Kaushik Halder', 'Kaushik.Halder@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARIJIT_KUNDU', 'Arijit Kundu', 'Arijit.Kundu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAIFMANIHAR_MANIHAR', 'Saifmanihar Manihar', 'Saifmanihar.Manihar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOMNATH_SADHU', 'Somnath Sadhu', 'Somnath.Sadhu@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SAYAN_BHATTACHARYA', 'Sayan Bhattacharya', 'Sayan.Bhattacharya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PURBITA_SUR', 'Purbita Sur', 'Purbita.Sur@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHAZIA_NASIM', 'Shazia Nasim', 'Shazia.Nasim@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('PIJUSH_BARMAN', 'Pijush Barman', 'Pijush.Barman@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHREASI_KHAN', 'Shreasi Khan', 'Shreasi.Khan@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DIPENDU_PAUL', 'Dipendu Paul', 'Dipendu.Paul@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOHINI_BHATTACHARYA', 'Sohini Bhattacharya', 'Sohini.Bhattacharya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHARUKH_HASAN', 'Sharukh Hasan', 'Sharukh.Hasan@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANISH_SARKAR', 'Anish Sarkar', 'Anish.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('VIVEK_KUMAR', 'Vivek Kumar', 'Vivek.Kumar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOMTIRTHA_MUKHOPADHYAY', 'Somtirtha Mukhopadhyay', 'Somtirtha.Mukhopadhyay@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RUPSA_ROY', 'Rupsa Roy', 'Rupsa.Roy@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRITAM_SHARMA', 'Pritam Sharma', 'Pritam.Sharma@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEEPU_SINGH', 'Deepu Singh', 'Deepu.Singh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('MANDRILA_LASKAR', 'Mandrila Laskar', 'Mandrila.Laskar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUBHOJIT_GUIN', 'Subhojit Guin', 'Subhojit.Guin@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ABHISRI_SHAHA', 'Abhisri Shaha', 'Abhisri.Shaha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('RIMSHA_AFREEN', 'Rimsha Afreen', 'Rimsha.Afreen@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUDESHNA_PATHAK', 'Sudeshna Pathak', 'Sudeshna.Pathak@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('INDRANJANA_CHATTERJEE', 'Indranjana Chatterjee', 'Indranjana.Chatterjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('NILANJAN_GHOSH', 'Nilanjan Ghosh', 'Nilanjan.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOURAV_BHATTACHARYYA', 'Sourav Bhattacharyya', 'Sourav.Bhattacharyya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ANJISHNU_SENGUPTA', 'Anjishnu Sengupta', 'Anjishnu.Sengupta@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', FALSE),
  ('CHANDRIMA_BASURI', 'Chandrima Basuri', 'Chandrima.Basuri@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('MOHIT_JENA', 'Mohit Jena', 'Mohit.Jena@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SACHIN_HAZRA', 'Sachin Hazra', 'Sachin.Hazra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRIYANSHU_PILANIWALA', 'Priyanshu Pilaniwala', 'Priyanshu.Pilaniwala@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SOUMIK_SINHA', 'Soumik Sinha', 'Soumik.Sinha@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AYUSH_CHHAJER', 'Ayush Chhajer', 'Ayush.Chhajer@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('AYAN_JANA', 'Ayan Jana', 'Ayan.Jana@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ARUNABHA_DUTTA', 'Arunabha Dutta', 'Arunabha.Dutta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ANKIT_SEN', 'Ankit Sen', 'Ankit.Sen@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHREYA_MUKHERJEE', 'Shreya Mukherjee', 'Shreya.Mukherjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYAN_DAS', 'Sayan Das', 'Sayan.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('JOYJIT_CHANDRA', 'Joyjit Chandra', 'Joyjit.Chandra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHASHANKA_CHATURVEDI', 'Shashanka Chaturvedi', 'Shashanka.Chaturvedi@hyland.com', 'Managed Services', 'OPS', 'HYBRID', 'KOLKATA', TRUE),
  ('AYAN_DASGUPTA', 'Ayan Dasgupta', 'Ayan.Dasgupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('KRITIKA_MOHTA', 'Kritika Mohta', 'Kritika.Mohta@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('SUSOBHAN_PANDIT', 'Susobhan Pandit', 'Susobhan.Pandit@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('INDRAJIT_BISWAS', 'Indrajit Biswas', 'Indrajit.Biswas@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAIKAT_BHATTACHARYA', 'Saikat Bhattacharya', 'Saikat.Bhattacharya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('UMASHANKAR_SINGH', 'Umashankar Singh', 'Umashankar.Singh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('BHASKARJYOTI_SARMA', 'Bhaskarjyoti Sarma', 'Bhaskarjyoti.Sarma@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('GOURAB_KARMAKAR', 'Gourab Karmakar', 'Gourab.Karmakar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SAYAN_BHOWMICK', 'Sayan Bhowmick', 'Sayan.Bhowmick@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AMIT_HEMBROM', 'Amit Hembrom', 'Amit.Hembrom@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MOU_DEY', 'Mou Dey', 'Mou.Dey@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SRIPIYA_CHOWDHURY', 'Sripiya Chowdhury', 'Sripiya.Chowdhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('DEBJIT_CHATTOPADHYAY', 'Debjit Chattopadhyay', 'Debjit.Chattopadhyay@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOUMYARUP_BOSE', 'Soumyarup Bose', 'Soumyarup.Bose@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('AMARJEET_RAJ', 'Amarjeet Raj', 'Amarjeet.Raj@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHRISTY_PRIYADARSHINI', 'Shristy Priyadarshini', 'Shristy.Priyadarshini@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RITABAN_MUKHERJEE', 'Ritaban Mukherjee', 'Ritaban.Mukherjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAKESH_BANERJEE', 'Rakesh Banerjee', 'Rakesh.Banerjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MEGHNA_ROYCHOWDHURY', 'Meghna Roychowdhury', 'Meghna.Roychowdhury@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYANI_SINHAROY', 'Sayani Sinharoy', 'Sayani.Sinharoy@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('SWAPNIL_DAS', 'Swapnil Das', 'Swapnil.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOURAV_NANDAN', 'Sourav Nandan', 'Sourav.Nandan@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('GOURAB_SEN', 'Gourab Sen', 'Gourab.Sen@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SOMNATH_DESHMUKH', 'Somnath Deshmukh', 'Somnath.Deshmukh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('PRIYAM_MAJUMDER', 'Priyam Majumder', 'Priyam.Majumder@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('NIGAMANANDA_JENA', 'Nigamananda Jena', 'Nigamananda.Jena@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SWAPNOJ_BANERJEE', 'Swapnoj Banerjee', 'Swapnoj.Banerjee@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ROHIT_GUPTA', 'Rohit Gupta', 'Rohit.Gupta@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', FALSE),
  ('AYAN_PANJI', 'Ayan Panji', 'Ayan.Panji@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('NISHANKUMAR_GHOSH', 'Nishankumar Ghosh', 'Nishankumar.Ghosh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAIKAT_MONDAL', 'Saikat Mondal', 'Saikat.Mondal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('UTTAM_KHARWAR', 'Uttam Kharwar', 'Uttam.Kharwar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AVISHIKTA_DAS', 'Avishikta Das', 'Avishikta.Das@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ASHUTOSH_RAI', 'Ashutosh Rai', 'Ashutosh.Rai@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('ROHAN_GOSWAMI', 'Rohan Goswami', 'Rohan.Goswami@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('KUNAL_RANA', 'Kunal Rana', 'Kunal.Rana@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANINDYA_BANDOPADHYAY', 'Anindya Bandopadhyay', 'Anindya.Bandopadhyay@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ABHAY_KHATTRY', 'Abhay Khattry', 'Abhay.Khattry@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYAN_PAL', 'Sayan Pal', 'Sayan.Pal@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('HARI_OM', 'Hari Om', 'Hari.Om@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('GURUDAS_BANERJEE', 'Gurudas Banerjee', 'Gurudas.Banerjee@hyland.com', 'Product Management', 'MANAGER', 'HYBRID', 'KOLKATA', TRUE),
  ('PRIYANKA_CHAKRABORTY', 'Priyanka Chakraborty', 'Priyanka.Chakraborty@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SHREYA_ROY', 'Shreya Roy', 'Shreya.Roy@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAYAN_DASGUPTA', 'Sayan Dasgupta', 'Sayan.Dasgupta@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ANAMIKA_DEY', 'Anamika Dey', 'Anamika.Dey@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('JAYSHRI_RATHOD', 'Jayshri Rathod', 'Jayshri.Rathod@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', FALSE),
  ('SHIBODAS_MALLICK', 'Shibodas Mallick', 'Shibodas.Mallick@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('SAHAMMAD_SEKH', 'Sahammad Sekh', 'Sahammad.Sekh@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBJIT_DEY', 'Debjit Dey', 'Debjit.Dey@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('AKASH_NAIK', 'Akash Naik', 'Akash.Naik@hyland.com', 'Cloud Platform Engineering', 'DEVOPS', 'HYBRID', 'KOLKATA', TRUE),
  ('JAYA_CHAUBEY', 'Jaya Chaubey', 'Jaya.Chaubey@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DEBJYOTI_CHAKRABORTY', 'Debjyoti Chakraborty', 'Debjyoti.Chakraborty@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ASWINI_MOHAPATRA', 'Aswini Mohapatra', 'Aswini.Mohapatra@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('DIPAYAN_DE', 'Dipayan De', 'Dipayan.De@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('RAKSHAK_SHAW', 'Rakshak Shaw', 'Rakshak.Shaw@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('GOPESH_PAUL', 'Gopesh Paul', 'Gopesh.Paul@hyland.com', 'Accounting and Finance', 'FINANCE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARITRA_PAKHIRA', 'Aritra Pakhira', 'Aritra.Pakhira@hyland.com', 'Information Systems', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('ARPITA_PRIYA', 'Arpita Priya', 'Arpita.Priya@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('MUDIT_TARWAY', 'Mudit Tarway', 'Mudit.Tarway@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('AVIRUP_CHOWDHURY', 'Avirup Chowdhury', 'Avirup.Chowdhury@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE),
  ('GOURAB_SARKAR', 'Gourab Sarkar', 'Gourab.Sarkar@hyland.com', 'Technology', 'EMPLOYEE', 'HYBRID', 'KOLKATA', TRUE)
ON CONFLICT (employee_id) DO UPDATE
  SET full_name       = EXCLUDED.full_name,
      email           = EXCLUDED.email,
      department      = EXCLUDED.department,
      role_code       = EXCLUDED.role_code,
      work_mode       = EXCLUDED.work_mode,
      office_location = EXCLUDED.office_location,
      active          = EXCLUDED.active;

COMMIT;